version: '3'
services:
  squid:
    build: ./
    container_name: ${CONTAINER_NAME:-squid}
    image: alpine-squid
    restart: unless-stopped

networks:
  default:
    external:
      name: ${NETWORK:-sshd}
